### PR TITLE
Upgrade v4.60.0

### LINKED ISSUE #1046: Upgrade terraform-provider-google-beta to v4.59.0
Release details: https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.59.0

### PR DESCRIPTION
**Pull request by danielrbradley**
Fixes #1046 

The v4.60.0 tag is not yet pushed but the release branch is already up - so should be able to jump straght to there.

### CODE REVIEW

**Comment by danielrbradley** [comment]
The upstream diff shows that `terraform-plugin-framework` has started to be addopted which explains the missing data sources - these are the first to be migrated across. cc: @iwahbe

**Comment by t0yv0** [comment]
What's your sense @danielrbradley about the missing functions. Should we prioritize getting these functions muxed in before doing a next release, or should we do a release anyway accepting that they are temporarily unavailable. Is there any usage data we should be consulting to influence this tradeoff?

**Comment by danielrbradley** [comment]
@t0yv0 these are pretty important functions so can't leave them out. I've prepped a patch to revert the conversions in our fork for now for this release. Then I think we should prioritise integrating the muxer for the subsequent release.

**Review by iwahbe — APPROVED** [review]
Looks good!

Can you explain the logic behind mapping all the `google_dataplex_lake_iam_*` to `"dataplex_lake_iam.html.markdown"`? How should we know to do that?

**Comment by danielrbradley** [comment]
@iwahbe I'm not too familiar with it either. 

tf_gen passed fine locally but failed in CI. I saw the other resources using it, so copied the pattern. I'd guess it's something to do with the docs not matching the naming convention expected by the bridge.

**Pull request merged**
