### PR TITLE
Add maxInstances and minInstances to CallbackFunctionArgs

### LINKED ISSUE #933: gcp.cloudfunctions.HttpCallbackFunction should support minInstances and maxInstances
Both properties are not available in the `HttpCallbackFunctionArgs` type for the HttpCallbackFunction convenience constructor.

Once deployed, I can set the min and max instances through GCP console, so these properties are valid.

### PR DESCRIPTION
**Pull request by thomasem**
Fixes #933 

Tested with the following (derived from [this example](https://github.com/pulumi/examples/blob/master/gcp-ts-functions/index.ts)):
```typescript
// Copyright 2016-2019, Pulumi Corporation.  All rights reserved.

import * as gcp from "@pulumi/gcp";

/**
 * Deploy a function using an explicitly set runtime.
 */
const runtime = "nodejs14"; // https://cloud.google.com/functions/docs/concepts/exec#runtimes
const greeting = new gcp.cloudfunctions.HttpCallbackFunction(`greeting-${runtime}`, {
    runtime: runtime,
    region: "us-east1",
    maxInstances: 2,
    minInstances: 2,
    callback: (req: any, res: any) => {
        res.send(`Greetings from ${req.body.name || "Google Cloud Functions"}!`);
    },
});

const invoker = new gcp.cloudfunctions.FunctionIamMember("invoker", {
    project: greeting.function.project,
    region: greeting.function.region,
    cloudFunction: greeting.function.name,
    role: "roles/cloudfunctions.invoker",
    member: "allUsers",
});

export const url = greeting.httpsTriggerUrl;
```

Pulumi output:

```
Updating (dev)

View Live: https://app.pulumi.com/thomasem/gcp-functions-issue-1/dev/updates/10

     Type                                        Name                       Status
 +   pulumi:pulumi:Stack                         gcp-functions-issue-1-dev  created (80s)
 +   ├─ gcp:cloudfunctions:CallbackFunction      greeting-nodejs14          created (0.51s)
 +   │  ├─ gcp:storage:Bucket                    greeting-nodejs14          created (1s)
 +   │  ├─ gcp:storage:BucketObject              greeting-nodejs14          created (0.66s)
 +   │  ├─ gcp:cloudfunctions:Function           greeting-nodejs14          created (74s)
 +   │  └─ gcp:cloudfunctions:FunctionIamMember  greeting-nodejs14-invoker  created (11s)
 +   └─ gcp:cloudfunctions:FunctionIamMember     invoker                    created (12s)


Outputs:
    url: "<REDACTED>"

Resources:
    + 7 created

Duration: 1m34s
```

And `gcloud`:
```
$ gcloud functions describe greeting-nodejs14-d5e1525
availableMemoryMb: 256
buildId: db673eef-558b-4836-b33f-5b4fbdde1e4c
buildName: projects/<REDACTED>/locations/us-east1/builds/db673eef-558b-4836-b33f-5b4fbdde1e4c
dockerRegistry: CONTAINER_REGISTRY
entryPoint: handler
httpsTrigger:
  securityLevel: SECURE_OPTIONAL
  url: <REDACTED>
ingressSettings: ALLOW_ALL
maxInstances: 2
minInstances: 2
name: <REDACTED>_greeting-nodejs14-d5e1525
runtime: nodejs14
serviceAccountEmail: <REDACTED>
sourceArchiveUrl: gs://greeting-nodejs14-bee2b70/greeting-nodejs14-152764b
status: ACTIVE
timeout: 60s
updateTime: '2023-02-28T16:59:57.872Z'
versionId: '1'
```
where we can see `maxInstances` and `minInstances` set. 😄

### CODE REVIEW

**Comment by kpitzen** [comment]
Hi @thomasem !  Thank you for your contribution here - the code and accompanying comments added are very much appreciated, and I thank you for verifying its correctness with an example.  I'll run the tests now.

**Comment by kpitzen** [comment]
The build passes!  Thanks again @thomasem - I'll get this merged now.

**Comment by thomasem** [comment]
@kpitzen right on! Thanks for the review / merge. 😄

**Pull request merged**
