### PR TITLE
Updating to terraform-provider-google-beta v.2.5.0

### PR DESCRIPTION
**Pull request by lukehoban**
Bring https://github.com/pulumi/pulumi-gcp/pull/137 over to a non-fork for testing.

### CODE REVIEW

**Comment by lukehoban** [comment]
@jen20 @stack72 Any idea why this is failing with:

```
[ umi/pulumi-gcp/examples/bucket ]     panic: fatal: An assertion has failed: Expected all Terraform resources in this module to have a 'google-beta_' prefix
[ umi/pulumi-gcp/examples/bucket ]     goroutine 1 [running]:
[ umi/pulumi-gcp/examples/bucket ]     github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
[ umi/pulumi-gcp/examples/bucket ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
[ umi/pulumi-gcp/examples/bucket ]     github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc000281e00, 0x228ca73, 0x45, 0xc0002f16f0, 0x1, 0x1)
[ umi/pulumi-gcp/examples/bucket ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x198
[ umi/pulumi-gcp/examples/bucket ]     github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).camelPascalPulumiName(0xc000312360, 0x2271c2a, 0x2c, 0x2c, 0x3960f60, 0x42d161, 0x22abe28)
[ umi/pulumi-gcp/examples/bucket ]     	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:274 +0xee
```

**Comment by stack72** [comment]
Hey @lukehoban, there looks to be a difference in the PRs. 

My PR uses this:

```
github.com/terraform-providers/terraform-provider-google-beta v0.0.0-20190418162215-5f98464803d1
```

Your PR uses this:

```
github.com/terraform-providers/terraform-provider-google-beta v0.0.0-20190422203630-616e8a9b048b
```

I just ran `make` from my fork using the ref above and I get the following:

```
▶ make
=============================
Google Cloud Platform Package
=============================
BUILD:
go install -ldflags "-X github.com/pulumi/pulumi-gcp/pkg/version.Version=v0.18.4-dev.1555511330+gca0325a" github.com/pulumi/pulumi-gcp/cmd/pulumi-resource-gcp
go: downloading github.com/terraform-providers/terraform-provider-google-beta v0.0.0-20190326192708-8ee58e6dda3c
go: extracting github.com/terraform-providers/terraform-provider-google-beta v0.0.0-20190326192708-8ee58e6dda3c
go install -ldflags "-X github.com/pulumi/pulumi-gcp/pkg/version.Version=v0.18.4-dev.1555511330+gca0325a" github.com/pulumi/pulumi-gcp/cmd/pulumi-tfgen-gcp
[ -x "/Users/stacko/.pulumi/bin/pulumi" ] || curl -fsSL https://get.pulumi.com | sh
pulumi plugin install resource random 0.2.0
warning: A new version of Pulumi is available. To upgrade from version '0.17.5' to '0.17.8', run
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.io/install for manual instructions and release notes.
[resource plugin random-0.2.0] installing
for LANGUAGE in "nodejs" "python" "go" ; do \
		pulumi-tfgen-gcp $LANGUAGE --overlays overlays/$LANGUAGE/ --out sdk/$LANGUAGE/ || exit 3 ; \
	done
warning: Expected to pair --- begin/end for resource google_container_node_pool's Markdown header
warning: Expected an H1 in markdown for resource google_container_node_pool
warning: Expected to pair --- begin/end for resource google_container_node_pool's Markdown header
warning: Expected an H1 in markdown for resource google_container_node_pool
warning: Could not find docs for resource google_project_iam_audit_config; consider overriding doc source location
```

**Comment by jen20** [comment]
> Expected all Terraform resources in this module to have a 'google-beta_' prefix

This should not be the case here - the prefix is set in resources.go to force resources to have the `google` prefix instead of `google-beta`: https://github.com/pulumi/pulumi-gcp/blob/master/resources.go#L93. I'll investigate why this is happening and get this merged and released.

**Comment by lukehoban** [comment]
> Your PR uses this: `github.com/terraform-providers/terraform-provider-google-beta v0.0.0-20190422203630-616e8a9b048b`

Yes - I added a commit to pull this forward to v2.5.1.  I'm not sure I did that "correctly" though.  @jen20 do we have documented the steps to update the version of the upstream provider?  I used `GO111MODULE=on go get  github.com/terraform-providers/terraform-provider-google-beta@616e8a9b048b0f29b9c783eefc112775997b8680`.  Is that sufficient?

**Comment by stack72** [comment]
@lukehoban that *should* be correct - I have been doing pretty much that to update

I am wondering if that particular commit in Terraform could be causing a problem itself

**Comment by lukehoban** [comment]
Going to try moving back to v2.5.0 for now and see if that works so we can merge to that release first.

**Comment by lukehoban** [comment]
Hmm - getting the same failures with v2.5.0 (@stack72's original changes).  Seems like this will need a deeper investigation from @jen20 or @stack72 to figure out what's causing that.

**Comment by jen20** [comment]
I've rebased #137 and opened #140 to cover these changes, so I'll go ahead and close this version.

**Pull request closed without merging**
