### PR TITLE
Update python example

### PR DESCRIPTION
**Pull request by AlexisMunera98**
This commit solves a reported issue in python example #580

### CODE REVIEW

**Comment by kpitzen** [comment]
Hi @AlexisMunera98 !  Thank you for opening this PR - it looks like it'll resolve a long-standing issue with our documentation.  I'll get the tests running now.

**Comment by kpitzen** [comment]
Hi @AlexisMunera98 - thanks again for opening this PR.  Per the test failure linked above, it looks like this issue originates with code generation in Python. There's a bit of strangeness with how things are named in GCP vs what idiomatic Python looks like. My guess is we need to add an exception in `resources.go` similar to what's done with NodeJS's naming exception there.

**Comment by iwahbe** [comment]
Hi @AlexisMunera98. It looks like this issue was closed in https://github.com/pulumi/pulumi-gcp/pull/1305:

https://github.com/pulumi/pulumi-gcp/blob/9edf26fac0772e0b87ad96f5342f9e171922cae6/sdk/python/pulumi_gcp/serviceaccount/account.py#L317-L319

https://github.com/pulumi/pulumi-gcp/blob/9edf26fac0772e0b87ad96f5342f9e171922cae6/sdk/python/pulumi_gcp/serviceaccount/account.py#L380-L383

**Pull request closed without merging**
