### PR TITLE
Make possible to add extraIncludePaths for cloud functions in node sdk

### LINKED ISSUE #148: Google cloud functions - Unable to access private npm repositories
- **Expected**
When deploying typescript google cloud functions, private npm repository pacakges are accessible
- **What happens**
Google cloud is not able to access the private packages because the `.npmrc` file with a valid read-only token to be uploaded to the function's repository. 

- Why
This is not available today for pulumi-gcp as ``` codePathOptions.extraIncludePaths not currently supported in GCP.```

- Steps to reproduce:

1. Setup typescript pulumi gcp project
2. Create new http google function referring to a private package:
```
import {parseText} from '@org/private_package';

import * as gcp from '@pulumi/gcp';

let greeting = new gcp.cloudfunctions.HttpCallbackFunction("hello", {
  callback: (req, res) => {
    // Change this code to fit your needs!
    res.send(parseText(`Greetings from ${req.body.name || 'Google Cloud Functions'}!`));
  },
  codePathOptions: {
    extraIncludePaths: ["./.npmrc"],
  },
});

export let url = greeting.httpsTriggerUrl;
```
3. `pulumi up`

- Logs:
```
Diagnostics:
  gcp:cloudfunctions:Function (hello):
    error: Plan apply failed: 1 error occurred:
        * creating urn:pulumi:gcp-functions-test::stackname::gcp:cloudfunctions:CallbackFunction$gcp:cloudfunctions/function:Function::hello: Error waiting for Creating CloudFunctions Function: Error code 3, message: Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`gen_package_lock` had stderr output:\nnpm ERR! code E404\nnpm ERR! 404 Not Found: @org/pirvate_repo@^0.0.3\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2019-05-15T17_44_52_086Z-debug.log\n\nerror: `gen_package_lock` returned code: 1", "errorType": "InternalError", "errorId": "F28126B7"}}
 
  pulumi:pulumi:Stack (stackname):
    error: update failed
```

### PR DESCRIPTION
**Pull request by pjbizon**
Fixes #148

### CODE REVIEW

**Comment by jkodroff** [comment]
@pjbizon Thanks so much for the contribution! I updated your PR description just so it has the magic words to close the related issue when this PR is merged.

**Comment by jkodroff** [comment]
@pjbizon Acceptance tests look good. Just waiting for review from someone more familiar with the node mixins.

**Comment by bartlomiejmichalski** [comment]
I have a question, when can this change be expected to happen? I must admit that it would also be useful to me in production. Thank you in advance for the information.

**Comment by stack72** [comment]
Hi @pjbizon 

thanks for the work here - sorry we didn't merge this sooner! This will go out as part of the next release of the provider

Paul

**Pull request merged**
