### PR TITLE
Enable TypedDict input types for the Python SDK

### PR DESCRIPTION
**Pull request by julienp**
Enable TypedDict input types for the Python SDK. The only manual change
is to set the InputTypes flag in the python language features of the
schema. This is done here https://github.com/pulumi/pulumi-gcp/pull/2116/commits/648c774c0b4397b46258f0ec9c88c380f909b5e5.
This flag is currently opt in, but will default to classes-and-dicts in
the future.

Epic https://github.com/pulumi/pulumi/issues/12689

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
Hey @julienp, thanks for the PR.

I spot-checked the changes and they looks sensible - I had one question, which I imagine is intended but:

```
if not MYPY:
    class AccessLevelConditionDevicePolicyArgsDict(TypedDict):
        allowed_device_management_levels: NotRequired[pulumi.Input[Sequence[pulumi.Input[str]]]]
        """
        A list of allowed device management levels.
        An empty list allows all management levels.
        Each value may be one of: `MANAGEMENT_UNSPECIFIED`, `NONE`, `BASIC`, `COMPLETE`.
        """
        allowed_encryption_statuses: NotRequired[pulumi.Input[Sequence[pulumi.Input[str]]]]
        """
        A list of allowed encryptions statuses.
        An empty list allows all statuses.
        Each value may be one of: `ENCRYPTION_UNSPECIFIED`, `ENCRYPTION_UNSUPPORTED`, `UNENCRYPTED`, `ENCRYPTED`.
        """
        os_constraints: NotRequired[pulumi.Input[Sequence[pulumi.Input['AccessLevelConditionDevicePolicyOsConstraintArgsDict']]]]
        """
        A list of allowed OS versions.
        An empty list allows all types and all versions.
        Structure is documented below.
        """
        require_admin_approval: NotRequired[pulumi.Input[bool]]
        """
        Whether the device needs to be approved by the customer admin.
        """
        require_corp_owned: NotRequired[pulumi.Input[bool]]
        """
        Whether the device needs to be corp owned.
        """
        require_screen_lock: NotRequired[pulumi.Input[bool]]
        """
        Whether or not screenlock is required for the DevicePolicy
        to be true. Defaults to false.
        """
elif False:
    AccessLevelConditionDevicePolicyArgsDict: TypeAlias = Mapping[str, Any]
```

this is a snippet from _inputs.py - is the `elif False:` the right way to give mypy the type alias?

Other than that the changes look fine to me.

Any idea of the risk associated with this change? If we think it's risky we'd generally start the rollout with less used providers.

**Comment by julienp** [comment]
> is the elif False: the right way to give mypy the type alias?

It definitely looks weird! MyPy has special handling for the `MYPY` variable and will always pick the else branch here. For MyPy alone it would also work with a plain `else:` instead of `elif False:`, but then other typecheckers can't eliminate that branch and get confused that there's potentially two types for the same `XXXArgsDict`.

**Comment by julienp** [comment]
> Any idea of the risk associated with this change? If we think it's risky we'd generally start the rollout with less used providers

We shipped it in `pulumi-aws`, so hopefully it won't blow up :) We can wait a little before merging this though if you prefer. I am reasonably confident about it though. 🤞

**Comment by VenelinMartinov** [comment]
If it's shipped in AWS then it's very likely to be fine here, so I am happy to merge.

**Review by VenelinMartinov — APPROVED** [review]

**Review by iwahbe — APPROVED** [review]

**Pull request merged**
